### ISSUE TITLE
Code Duplication

### ISSUE THREAD

**Issue by selvianu** [csys-fresher-batch-2021/carserviceapp-core#3]
Code duplication : Connection Util method is duplicated is all DAO classes.
RegistrationDAO
ListAll_Booked_ServiceDAO

**Comment by nandhini2424** [comment]
done

**Comment by selvianu** [comment]
Issue - Not resolved

String driverClassName = "oracle.jdbc.driver.OracleDriver";		
				String url = "jdbc:oracle:thin:@192.168.0.20:1521:DBEBS12";		
				String username = "apps";		
				String password = "apps";
Move this snippet into a separate method and call the method wherever you need DB Connection.

**Comment by nandhini2424** [comment]
issue corrected

**Comment by selvianu** [comment]
Nandhini, Create a separate method for above snippet and wherever you need the connection of DB - call that method. 
In all the DAO it is repeated. In the entire project it should be in only one class

![image](https://user-images.githubusercontent.com/22638364/126420471-8932ad9b-1def-47f2-883a-12d5f0421e34.png)

![image](https://user-images.githubusercontent.com/22638364/126420502-07900ca1-6f87-4ff3-8616-be5dd547ba2e.png)


![image](https://user-images.githubusercontent.com/22638364/126420919-fb94cc8e-541e-48c7-b769-46144b8abaf6.png)

**Comment by nareshkumar-h** [comment]
Code should not be duplicated. Fix

**Comment by nandhini2424** [comment]
corrected

**Comment by selvianu** [comment]
working as expected. closed

**Comment by nandhini2424** [comment]
Thank you mam.
